<?php if(!empty($flash)): ?>
    <ul>
    <?php foreach($flash['success'] as $successMessage): ?>
    <li><font color="green"><?= $successMessage ?></font></li> 
    <?php endforeach ?>
    </ul>
<?php endif ?>

<form action="/users" method="get">
    <label> Search
        <input type="search" required name="term" value="<?= htmlspecialchars($term) ?>" />
    </label>
</form>



<?php foreach($users as $user): ?>
    <div>
        <?php if (!isset($user['deleted'])): ?>
        <a href="/users/<?= $user['id'] ?>"><?= htmlspecialchars($user['name']) ?></a> 
        <form action="/users/<?= $user['id'] ?>" method="post">
        <input type="hidden" name="_METHOD" value="DELETE">
        <input type="submit" value="Remove">
        </form>
        <?php endif ?>
    </div>
<?php endforeach ?>


<br>
<a href="/users">All users</a> 
<a href="/users/new">New user</a> 
