<form action="/users" method="post">
    <div>
        <label>
            Nickame
            <input type="text" name="user[name]" value="<?= $user['name'] ?>">
        </label>
            <?php if (isset($errors['name'])): ?>
            <label><font color="darkred"><?= $errors['name']; ?></font><label>
            <?php endif ?>
    </div>
    <div>
        <label>
            Email
            <input type="email" required name="user[email]" value="<?= $user['email'] ?>">
        </label>
            <?php if (isset($errors['email'])): ?>
            <label><font color="darkred"><?= $errors['email']; ?></font><label>
            <?php endif ?>
    </div>
    <input type="submit" value="Sign up">
</form>