<?php if(!empty($flash)): ?>
    <ul>
    <?php foreach($flash['success'] as $successMessage): ?>
    <li><font color="green"><?= $successMessage ?></font></li> 
    <?php endforeach ?>
    </ul>
<?php endif ?>

<h1>Hello, <?= htmlspecialchars($nickname) ?></h1>
<h2>Your id: <?= htmlspecialchars($id) ?></h2>

<div>
    <label>
        <a href="/users/<?= $id ?>/edit">Edit info</a>
    </label>
</div>
<div>
    <label>
        <a href="/users">to all Users</a>
    </label>
</div>